# Generated by Django 3.2.4 on 2021-10-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='avatar',
            field=models.ImageField(upload_to='core'),
        ),
    ]
