# Generated by Django 3.2.4 on 2021-10-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_curso_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
