# Generated by Django 3.2.4 on 2021-11-04 20:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_curso_disciplina'),
        ('visitante', '0002_recomendacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
    ]
